# LOAN DEFAULT DATASET CLEANING
## THIS NOTE BOOK IS FOR EXPLORATORY ANALYSIS OF THE LOAN DATASET

The original csv file contains 215257 records and 102 fields.
Many of the fields were irrelevant to my cause, as I want to build a model that takes basic demographic and financial data and predict whether or not a loan applicant will default on his or her loan or not.

## CHOSEN COLUMNS
    'DAYS_AGE',
    'NAME_INCOME_TYPE',
    'DAYS_EMPLOYMENT',
    'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS',
    'CNT_CHILDREN',
    'CNT_FAM_MEMBERS',
    'AMT_INCOME_TOTAL',
    'FLAG_OWN_CAR',
    'FLAG_OWN_REALTY',
    'NAME_HOUSING_TYPE',
    'AMT_CREDIT',
    'TARGET'

***The target column has only two kinds of response 0(For an applicant that didn't default) and 1 (For an applicant that default.***


## Missing Values
Only a few records had missing values in some columns, *i.e after picking my preferred columns*, so I decided to drop them as they were not many.

## FINAL DATA SHAPE
215255 records X 15 columns (including ID and Target)
**17448 were loan defaulters**

In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [47]:
df = pd.read_csv("data/train.csv")

In [48]:
df

,ID,NAME_CONTRACT_TYPE,GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,...,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,EXT_SOURCE_4,TARGET
0,160132,Cash loans,F,N,Y,0,427500.0,1288350.0,37800.0,1125000.0,...,0,0,0.0,0.0,1.0,0.0,0.0,5.0,0.242982,0
1,233132,Cash loans,M,Y,Y,0,180000.0,848745.0,40963.5,675000.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.115508,0
2,307771,Cash loans,M,Y,Y,1,112500.0,385164.0,19795.5,292500.0,...,0,0,0.0,0.0,0.0,0.0,0.0,4.0,0.393106,0
3,376452,Cash loans,F,N,Y,0,540000.0,1433520.0,60867.0,1237500.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.455985,0
4,405403,Cash loans,M,Y,Y,0,76500.0,900000.0,26316.0,900000.0,...,0,0,0.0,0.0,0.0,3.0,0.0,2.0,0.141508,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215252,308750,Cash loans,M,Y,N,0,144000.0,701730.0,70956.0,675000.0,...,0,0,0.0,0.0,0.0,0.0,1.0,1.0,0.139248,0
215253,451252,Cash loans,M,N,N,1,148500.0,254700.0,14751.0,225000.0,...,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.135489,0
215254,103357,Cash loans,F,Y,Y,0,270000.0,1030500.0,30258.0,1030500.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.131298,0
215255,244766,Cash loans,F,N,Y,0,225000.0,433057.5,19206.0,324000.0,...,0,0,0.0,0.0,0.0,1.0,0.0,5.0,0.128493,1
215256,450477,Cash loans,F,N,Y,0,189000.0,954207.0,28030.5,796500.0,...,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.561921,0

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215257 entries, 0 to 215256
Columns: 102 entries, ID to TARGET
dtypes: float64(48), int64(40), object(14)
memory usage: 167.5+ MB

In [50]:
df.describe()

,ID,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,DAYS_AGE,DAYS_EMPLOYMENT,DAYS_ID_PUBLISH,OWN_CAR_AGE,...,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,EXT_SOURCE_4,TARGET
count,215257.000000,215257.000000,2.152570e+05,2.152570e+05,215249.000000,2.150540e+05,215257.000000,215257.000000,215257.000000,73305.000000,...,215257.000000,215257.000000,186162.000000,186162.000000,186162.000000,186162.000000,186162.000000,186162.00000,2.147930e+05,215257.000000
mean,277916.285552,0.416567,1.683448e+05,5.996394e+05,27128.366938,5.388528e+05,-16040.968814,64138.989292,-2995.073206,12.053175,...,0.000506,0.000330,0.006494,0.006935,0.034486,0.268175,0.265264,1.90107,2.571639e-01,0.081057
std,102805.880546,0.721898,1.023409e+05,4.030145e+05,14521.116795,3.699160e+05,4367.736464,141546.368713,1509.053098,11.920288,...,0.022497,0.018158,0.084051,0.108859,0.203859,0.922865,0.860637,1.86733,1.850209e-01,0.272923
min,100002.000000,0.000000,2.565000e+04,4.500000e+04,1615.500000,4.050000e+04,-25201.000000,-17912.000000,-6383.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,2.436734e-08,0.000000
25%,188825.000000,0.000000,1.125000e+05,2.700000e+05,16551.000000,2.385000e+05,-19697.000000,-2758.000000,-4298.000000,5.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,9.779965e-02,0.000000
50%,277695.000000,0.000000,1.462500e+05,5.155290e+05,24930.000000,4.500000e+05,-15756.000000,-1209.000000,-3257.000000,9.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.00000,2.257796e-01,0.000000
75%,366772.000000,1.000000,2.025000e+05,8.086500e+05,34605.000000,6.795000e+05,-12409.000000,-288.000000,-1722.000000,15.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.00000,3.940680e-01,0.000000
max,456255.000000,19.000000,9.000000e+06,4.050000e+06,230161.500000,4.050000e+06,-7676.000000,365243.000000,0.000000,91.000000,...,1.000000,1.000000,3.000000,9.000000,8.000000,27.000000,261.000000,25.00000,8.059096e-01,1.000000

In [51]:
# 1. Define the exact list of columns you want to keep
columns_to_keep = [
    'DAYS_AGE',
    'NAME_INCOME_TYPE',
    'DAYS_EMPLOYMENT',
    'NAME_EDUCATION_TYPE',
    'NAME_FAMILY_STATUS',
    'CNT_CHILDREN',
    'CNT_FAM_MEMBERS',
    'AMT_INCOME_TOTAL',
    'FLAG_OWN_CAR',
    'FLAG_OWN_REALTY',
    'NAME_HOUSING_TYPE',
    'AMT_CREDIT',
    'TARGET'
]

# 2. Subset the dataframe to only include these columns
# We create a new variable 'df_final' so you don't overwrite df_cleaned by mistake
df_final = df[columns_to_keep]

# Verify your final, lean dataframe
print("Final DataFrame Shape:", df_final.shape)
print("\nFirst 3 rows:")
print(df_final.head(3))

Final DataFrame Shape: (215257, 13)

First 3 rows:
   DAYS_AGE      NAME_INCOME_TYPE  DAYS_EMPLOYMENT  \
0    -22008             Pensioner           365243
1     -8506  Commercial associate             -313
2    -11579               Working            -2651

             NAME_EDUCATION_TYPE    NAME_FAMILY_STATUS  CNT_CHILDREN  \
0  Secondary / secondary special                 Widow             0
1  Secondary / secondary special  Single / not married             0
2  Secondary / secondary special               Married             1

   CNT_FAM_MEMBERS  AMT_INCOME_TOTAL FLAG_OWN_CAR FLAG_OWN_REALTY  \
0              1.0          427500.0            N               Y
1              1.0          180000.0            Y               Y
2              3.0          112500.0            Y               Y

   NAME_HOUSING_TYPE  AMT_CREDIT  TARGET
0  House / apartment   1288350.0       0
1  House / apartment    848745.0       0
2   Rented apartment    385164.0       0

In [52]:
missing_counts = df_final.isnull().sum()

# (Optional) Filter to only show columns that actually have missing values > 0
missing_counts = missing_counts[missing_counts > 0]
print("--- Missing Values in Remaining Columns ---")
print(missing_counts)
print("\n")


# 2. Split into Numerical and Categorical so you can plan your imputation
# Grab just the columns from df_cleaned that have missing values
cols_with_missing = missing_counts.index

# Separate them by data type
numerical_cols = df_final[cols_with_missing].select_dtypes(include=['number']).columns
categorical_cols = df_final[cols_with_missing].select_dtypes(exclude=['number']).columns

print("--- Numerical Columns to fill with Median ---")
print(df_final[numerical_cols].isnull().sum())

print("\n--- Categorical Columns to fill with Mode/Unknown ---")
print(df_final[categorical_cols].isnull().sum())

--- Missing Values in Remaining Columns ---
CNT_FAM_MEMBERS    2
dtype: int64


--- Numerical Columns to fill with Median ---
CNT_FAM_MEMBERS    2
dtype: int64

--- Categorical Columns to fill with Mode/Unknown ---
Series([], dtype: float64)

In [53]:
rows_to_check = ['CNT_FAM_MEMBERS']
df_final = df_final.dropna(subset=rows_to_check)

In [54]:
df_final.shape

(215255, 13)

In [55]:
df_final

,DAYS_AGE,NAME_INCOME_TYPE,DAYS_EMPLOYMENT,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,CNT_CHILDREN,CNT_FAM_MEMBERS,AMT_INCOME_TOTAL,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,AMT_CREDIT,TARGET
0,-22008,Pensioner,365243,Secondary / secondary special,Widow,0,1.0,427500.0,N,Y,House / apartment,1288350.0,0
1,-8506,Commercial associate,-313,Secondary / secondary special,Single / not married,0,1.0,180000.0,Y,Y,House / apartment,848745.0,0
2,-11579,Working,-2651,Secondary / secondary special,Married,1,3.0,112500.0,Y,Y,Rented apartment,385164.0,0
3,-21179,Pensioner,365243,Secondary / secondary special,Married,0,2.0,540000.0,N,Y,House / apartment,1433520.0,0
4,-21210,Working,-13767,Secondary / secondary special,Married,0,2.0,76500.0,Y,Y,House / apartment,900000.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
215252,-18441,Working,-1540,Secondary / secondary special,Married,0,2.0,144000.0,Y,N,House / apartment,701730.0,0
215253,-10592,Working,-2360,Secondary / secondary special,Married,1,3.0,148500.0,N,N,With parents,254700.0,0
215254,-15598,Commercial associate,-2105,Incomplete higher,Civil marriage,0,2.0,270000.0,Y,Y,House / apartment,1030500.0,0
215255,-19451,Working,-1650,Secondary / secondary special,Separated,0,1.0,225000.0,N,Y,House / apartment,433057.5,1
215256,-19117,Working,-1505,Secondary / secondary special,Married,0,2.0,189000.0,N,Y,House / apartment,954207.0,0

In [56]:
df_final['AGE_YEARS'] = abs(df_final['DAYS_AGE']) // 365
df_final['YEARS_EMPLOYED'] = abs(df_final['DAYS_EMPLOYMENT']) // 365

df_final = df_final.drop(columns=['DAYS_AGE', 'DAYS_EMPLOYMENT'])
df_final

,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,CNT_CHILDREN,CNT_FAM_MEMBERS,AMT_INCOME_TOTAL,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,AMT_CREDIT,TARGET,AGE_YEARS,YEARS_EMPLOYED
0,Pensioner,Secondary / secondary special,Widow,0,1.0,427500.0,N,Y,House / apartment,1288350.0,0,60,1000
1,Commercial associate,Secondary / secondary special,Single / not married,0,1.0,180000.0,Y,Y,House / apartment,848745.0,0,23,0
2,Working,Secondary / secondary special,Married,1,3.0,112500.0,Y,Y,Rented apartment,385164.0,0,31,7
3,Pensioner,Secondary / secondary special,Married,0,2.0,540000.0,N,Y,House / apartment,1433520.0,0,58,1000
4,Working,Secondary / secondary special,Married,0,2.0,76500.0,Y,Y,House / apartment,900000.0,0,58,37
...,...,...,...,...,...,...,...,...,...,...,...,...,...
215252,Working,Secondary / secondary special,Married,0,2.0,144000.0,Y,N,House / apartment,701730.0,0,50,4
215253,Working,Secondary / secondary special,Married,1,3.0,148500.0,N,N,With parents,254700.0,0,29,6
215254,Commercial associate,Incomplete higher,Civil marriage,0,2.0,270000.0,Y,Y,House / apartment,1030500.0,0,42,5
215255,Working,Secondary / secondary special,Separated,0,1.0,225000.0,N,Y,House / apartment,433057.5,1,53,4
215256,Working,Secondary / secondary special,Married,0,2.0,189000.0,N,Y,House / apartment,954207.0,0,52,4

# NOTE:
The cell below takes care of the abnormal 1000 years employment age. and adds a new column FLAG_EMP_ANOMALY to track for and differentiate the abnormal cells from the regular cells for those with just 0 years of experience

In [60]:
abnormal_age_count = (df_final['AGE_YEARS'] > 70).sum()
print(f"Number of people over 70 years old: {abnormal_age_count}")

# 2. Count unrealistic employment lengths (e.g., working > 50 years)
abnormal_emp_count = (df_final['YEARS_EMPLOYED'] > 50).sum()
print(f"Number of people working > 50 years: {abnormal_emp_count}")

anomaly_value = 1000
df_final['YEARS_EMPLOYED'] = df_final['YEARS_EMPLOYED'].replace(anomaly_value, np.nan)
df_final['FLAG_EMP_ANOMALY'] = df_final['YEARS_EMPLOYED'].isnull().astype(int)
df_final['YEARS_EMPLOYED'] = df_final['YEARS_EMPLOYED'].fillna(0)

df_final

Number of people over 70 years old: 0
Number of people working > 50 years: 38952

,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,CNT_CHILDREN,CNT_FAM_MEMBERS,AMT_INCOME_TOTAL,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,AMT_CREDIT,TARGET,AGE_YEARS,YEARS_EMPLOYED,FLAG_EMP_ANOMALY
0,Pensioner,Secondary / secondary special,Widow,0,1.0,427500.0,N,Y,House / apartment,1288350.0,0,60,0.0,1
1,Commercial associate,Secondary / secondary special,Single / not married,0,1.0,180000.0,Y,Y,House / apartment,848745.0,0,23,0.0,0
2,Working,Secondary / secondary special,Married,1,3.0,112500.0,Y,Y,Rented apartment,385164.0,0,31,7.0,0
3,Pensioner,Secondary / secondary special,Married,0,2.0,540000.0,N,Y,House / apartment,1433520.0,0,58,0.0,1
4,Working,Secondary / secondary special,Married,0,2.0,76500.0,Y,Y,House / apartment,900000.0,0,58,37.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215252,Working,Secondary / secondary special,Married,0,2.0,144000.0,Y,N,House / apartment,701730.0,0,50,4.0,0
215253,Working,Secondary / secondary special,Married,1,3.0,148500.0,N,N,With parents,254700.0,0,29,6.0,0
215254,Commercial associate,Incomplete higher,Civil marriage,0,2.0,270000.0,Y,Y,House / apartment,1030500.0,0,42,5.0,0
215255,Working,Secondary / secondary special,Separated,0,1.0,225000.0,N,Y,House / apartment,433057.5,1,53,4.0,0
215256,Working,Secondary / secondary special,Married,0,2.0,189000.0,N,Y,House / apartment,954207.0,0,52,4.0,0

# NOTE

A new column 'CREDIT_TO_INCOME_RATIO' was build to re the different currency problem

In [65]:
df_final['CREDIT_TO_INCOME_RATIO'] = df_final['AMT_CREDIT'] / df_final['AMT_INCOME_TOTAL']
df_final

,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,CNT_CHILDREN,CNT_FAM_MEMBERS,AMT_INCOME_TOTAL,FLAG_OWN_CAR,FLAG_OWN_REALTY,NAME_HOUSING_TYPE,AMT_CREDIT,TARGET,AGE_YEARS,YEARS_EMPLOYED,FLAG_EMP_ANOMALY,CREDIT_TO_INCOME_RATIO
0,Pensioner,Secondary / secondary special,Widow,0,1.0,427500.0,N,Y,House / apartment,1288350.0,0,60,0.0,1,3.013684
1,Commercial associate,Secondary / secondary special,Single / not married,0,1.0,180000.0,Y,Y,House / apartment,848745.0,0,23,0.0,0,4.715250
2,Working,Secondary / secondary special,Married,1,3.0,112500.0,Y,Y,Rented apartment,385164.0,0,31,7.0,0,3.423680
3,Pensioner,Secondary / secondary special,Married,0,2.0,540000.0,N,Y,House / apartment,1433520.0,0,58,0.0,1,2.654667
4,Working,Secondary / secondary special,Married,0,2.0,76500.0,Y,Y,House / apartment,900000.0,0,58,37.0,0,11.764706
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
215252,Working,Secondary / secondary special,Married,0,2.0,144000.0,Y,N,House / apartment,701730.0,0,50,4.0,0,4.873125
215253,Working,Secondary / secondary special,Married,1,3.0,148500.0,N,N,With parents,254700.0,0,29,6.0,0,1.715152
215254,Commercial associate,Incomplete higher,Civil marriage,0,2.0,270000.0,Y,Y,House / apartment,1030500.0,0,42,5.0,0,3.816667
215255,Working,Secondary / secondary special,Separated,0,1.0,225000.0,N,Y,House / apartment,433057.5,1,53,4.0,0,1.924700
215256,Working,Secondary / secondary special,Married,0,2.0,189000.0,N,Y,House / apartment,954207.0,0,52,4.0,0,5.048714

In [13]:
df_final['TARGET'].sum()

np.int64(17448)

In [64]:
df_final.describe()

,CNT_CHILDREN,CNT_FAM_MEMBERS,AMT_INCOME_TOTAL,AMT_CREDIT,TARGET,AGE_YEARS,YEARS_EMPLOYED,FLAG_EMP_ANOMALY,CREDIT_TO_INCOME_RATIO
count,215255.000000,215255.000000,2.152550e+05,2.152550e+05,215255.000000,215255.000000,215255.000000,215255.000000,215255.000000
mean,0.416571,2.150882,1.683434e+05,5.996391e+05,0.081057,43.447335,4.948350,0.180957,3.962231
std,0.721900,0.910791,1.023395e+05,4.030163e+05,0.272924,11.965317,6.259011,0.384984,2.694621
min,0.000000,1.000000,2.565000e+04,4.500000e+04,0.000000,21.000000,0.000000,0.000000,0.076190
25%,0.000000,2.000000,1.125000e+05,2.700000e+05,0.000000,33.000000,0.000000,0.000000,2.018667
50%,0.000000,2.000000,1.462500e+05,5.155290e+05,0.000000,43.000000,3.000000,0.000000,3.266640
75%,1.000000,3.000000,2.025000e+05,8.086500e+05,0.000000,53.000000,7.000000,0.000000,5.168514
max,19.000000,20.000000,9.000000e+06,4.050000e+06,1.000000,69.000000,49.000000,1.000000,84.736842

## EXPLORATORY DATA ANALYSIS

In [14]:
ss

NameError: name 'ss' is not defined